version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    restart: 'no'

    environment:
      POSTGRES_DB: 'groundwork'
      POSTGRES_USER: 'groundwork'
      POSTGRES_PASSWORD: 'groundwork'

    ports:
      - '5432:5432'

  mariadb:
    image: 'mariadb:10'
    restart: 'no'

    environment:
      MARIADB_DATABASE: 'groundwork'
      MARIADB_USER: 'groundwork'
      MARIADB_PASSWORD: 'groundwork'
      MARIADB_RANDOM_ROOT_PASSWORD: 'true'

    ports:
      - '3306:3306'
