version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    restart: 'no'

    environment:
      POSTGRES_DB: 'noorm'
      POSTGRES_USER: 'noorm'
      POSTGRES_PASSWORD: 'noorm'

    ports:
      - '5432:5432'

  mariadb:
    image: 'mariadb:10'
    restart: 'no'

    environment:
      MARIADB_DATABASE: 'noorm'
      MARIADB_USER: 'noorm'
      MARIADB_PASSWORD: 'noorm'
      MARIADB_RANDOM_ROOT_PASSWORD: 'true'

    ports:
      - '3306:3306'
